In [1]:
from pathlib import Path
while not (Path.cwd() / '.git').exists():
    %cd ..

/home/matthew/study/grab-voc-triage

In [12]:
import pandas as pd
import config
import numpy as np
from sklearn import metrics

In [4]:
df_mini = pd.read_csv("data/processed/manual_annotation_openai_annotated.csv")
df_mini.head(2)

,Unnamed: 0.1,Unnamed: 0,userName,score,at,content,DRIVER_OPS,APP_AND_MAPS,PRICING_AND_BILLING,FULFILLMENT_FOOD,DRIVER_OPS.1,APP_AND_MAPS.1,PRICING_AND_BILLING.1,FULFILLMENT_FOOD.1
0,0,141,Pengguna Google,1,2026-08-29 11:18:30,gak tau kenapa udah gak kayak dulu lagi pakai ...,NEG,ABSENT,ABSENT,ABSENT,ABSENT,ABSENT,ABSENT,NEG
1,1,320,Pengguna Google,1,2026-08-22 00:49:40,skrang grab jelek banget driver nya gapernah d...,NEG,ABSENT,ABSENT,ABSENT,NEG,ABSENT,ABSENT,NEG

In [9]:
df_4o = pd.read_csv("data/processed/manual_annotation_gpt4o.csv")
df_4o

,Unnamed: 0,userName,score,at,content,DRIVER_OPS,APP_AND_MAPS,PRICING_AND_BILLING,FULFILLMENT_FOOD,DRIVER_OPS.1,APP_AND_MAPS.1,PRICING_AND_BILLING.1,FULFILLMENT_FOOD.1
0,141,Pengguna Google,1,2026-08-29 11:18:30,gak tau kenapa udah gak kayak dulu lagi pakai ...,NEG,ABSENT,ABSENT,ABSENT,ABSENT,ABSENT,NEG,ABSENT
1,320,Pengguna Google,1,2026-08-22 00:49:40,skrang grab jelek banget driver nya gapernah d...,NEG,ABSENT,ABSENT,ABSENT,NEG,ABSENT,ABSENT,ABSENT
2,1335,Pengguna Google,1,2026-07-15 11:54:04,driver nya gak jujur jelas naro titik sudah be...,NEG,ABSENT,ABSENT,ABSENT,NEG,ABSENT,ABSENT,ABSENT
3,1496,Pengguna Google,1,2026-07-08 13:57:12,knpa sya ksi bintang satu karna ada kurir kura...,NEG,ABSENT,ABSENT,ABSENT,NEG,ABSENT,NEG,ABSENT
4,2216,Pengguna Google,1,2026-06-09 16:32:58,jelek banget pelayanannya kurang dan sering bu...,ABSENT,NEG,NEG,ABSENT,ABSENT,NEG,NEG,ABSENT
5,541,Pengguna Google,1,2026-08-14 16:51:14,pembaruan makin ke sini makin memburuk terutam...,ABSENT,NEG,ABSENT,ABSENT,ABSENT,NEG,ABSENT,ABSENT
6,2067,Pengguna Google,1,2026-06-20 17:46:25,sekarang masukin no hp pun eroor apalah ini,ABSENT,NEG,ABSENT,ABSENT,ABSENT,NEG,ABSENT,ABSENT
7,480,Pengguna Google,1,2026-08-16 19:56:44,lucu deh ni apk ga usah ada option hemat kalo ...,NEG,ABSENT,NEG,ABSENT,ABSENT,NEG,ABSENT,ABSENT
8,3248,Dendo Se,1,2026-05-02 15:56:01,wkwkwk sangat2 tidak worth it aplikasi nya ove...,ABSENT,ABSENT,NEG,ABSENT,ABSENT,NEG,NEG,ABSENT
9,205,Pengguna Google,1,2026-08-26 17:40:05,pdhl alamat udh sesuai titik tpi mlh app nya n...,ABSENT,NEG,ABSENT,ABSENT,ABSENT,NEG,ABSENT,ABSENT
10,1796,Pengguna Google,1,2026-06-29 13:24:33,app ga jelas mending yang lain jangan grab ya,ABSENT,NEG,ABSENT,ABSENT,ABSENT,NEG,ABSENT,ABSENT
11,2950,Pengguna Google,1,2026-05-13 21:21:03,saya bayar ongkos grab bike menggunakan qris k...,ABSENT,ABSENT,NEG,ABSENT,ABSENT,ABSENT,NEG,ABSENT
12,936,Pengguna Google,1,2026-07-31 21:45:26,baru juga daftar kok dh dibilang berkali kali sih,ABSENT,NEG,ABSENT,ABSENT,ABSENT,NEG,ABSENT,ABSENT
13,1651,Pengguna Google,1,2026-07-03 09:36:58,grabb bike hemat bulan juni jarak 1 km dari ru...,ABSENT,ABSENT,NEG,ABSENT,ABSENT,ABSENT,NEG,ABSENT
14,1886,Pengguna Google,1,2026-06-27 02:14:27,malah di tangguhkan padahal ga melakukan salah...,ABSENT,NEG,ABSENT,ABSENT,ABSENT,NEG,ABSENT,ABSENT
15,863,Pengguna Google,1,2026-08-03 08:11:48,di iklan masih 7rb tapi di aplikasi 9rb,ABSENT,ABSENT,NEG,ABSENT,ABSENT,ABSENT,NEG,ABSENT
16,684,Pengguna Google,1,2026-08-09 01:58:03,saya 1jm nunguin pesanan saya di antar malah d...,NEG,ABSENT,ABSENT,ABSENT,NEG,ABSENT,ABSENT,ABSENT
17,456,Pengguna Google,1,2026-08-17 12:24:37,saya pesan makanan ternyata resto tutup dan hp...,ABSENT,ABSENT,ABSENT,NEG,ABSENT,NEG,ABSENT,NEG
18,3082,Pengguna Google,1,2026-05-08 17:54:05,5 kali pesan grab hemat tidak tawar harga 5 ka...,NEG,ABSENT,ABSENT,ABSENT,NEG,ABSENT,ABSENT,ABSENT
19,916,Pengguna Google,1,2026-08-01 19:01:16,grab aplikasi lu dah paling bagus tp soal titi...,NEG,ABSENT,ABSENT,ABSENT,NEG,NEG,ABSENT,ABSENT
20,3322,Risky Nia,1,2026-04-29 16:35:20,jaringan bagus di apk nya tidak ada jaringan,ABSENT,NEG,ABSENT,ABSENT,ABSENT,NEG,ABSENT,ABSENT
21,3493,Elisabet Suryanti Ndelos,1,2026-04-22 16:10:48,aplikasi paling aneh bisa pilih makanan menu p...,ABSENT,NEG,ABSENT,ABSENT,ABSENT,NEG,ABSENT,ABSENT
22,2228,Pengguna Google,1,2026-06-09 11:54:45,saya turunkan penilaian saya dikarenakan tidak...,ABSENT,NEG,ABSENT,ABSENT,ABSENT,NEG,ABSENT,ABSENT
23,862,Pengguna Google,2,2026-08-03 10:00:08,kok grabunlimitied tiba2 hilang padahal saya i...,ABSENT,ABSENT,NEG,ABSENT,ABSENT,ABSENT,NEG,ABSENT
24,686,Pengguna Google,2,2026-08-08 21:06:58,aplikasi kikir anjir checkout penggaris harga ...,ABSENT,ABSENT,NEG,ABSENT,ABSENT,ABSENT,NEG,ABSENT
25,1910,Pengguna Google,2,2026-06-26 02:08:33,ya ampun mau ganti nama aja susah di buat mute...,ABSENT,NEG,ABSENT,ABSENT,ABSENT,NEG,ABSENT,ABSENT
26,2490,Pengguna Google,2,2026-05-31 13:50:38,saya sdh bertahun tahun memakai grab dan serin...,NEG,ABSENT,ABSENT,ABSENT,NEG,ABSENT,ABSENT,ABSENT
27,1154,Pengguna Google,3,2026-07-22 06:39:03,hrsnya makanan umkm dpt diskon 10 bnyk makanan...,ABSENT,ABSENT,NEG,ABSENT,ABSENT,ABSENT,NEG,ABSENT
28,1397,Pengguna Google,3,2026-07-12 14:25:52,nak cari grab dekat kuala lumpur susah kali ma...,NEG,ABSENT,NEG,ABSENT,ABSENT,ABSENT,NEG,ABSENT
29,1000,Pengguna Google,3,2026-07-28 22:41:46,kenapa belakangan ini diskon nya ga adaa malah...,ABSENT,ABSENT,NEG,ABSENT,ABSENT,ABSENT,NEG,ABSENT
30,3144,Pengguna Google,3,2026-05-06 17:06:12,semakin kesini semakin gak karuan gaada promo ...,ABSENT,ABSENT,NEG,ABSENT,ABSENT,ABSENT,NEG,ABSENT
31,2640,Pengguna Google,4,2026-05-26 10:48:56,apaan sii ini aplikasi grep kan bisa nanti abd...,ABSENT,NEG,ABSENT,ABSENT,ABSENT,NEG,ABSENT,ABSENT
32,3356,Adi bayu,4,2026-04-28 14:40:05,coba grab ni malah ngasih fitur reseh mau mese...,ABSENT,NEG,ABSENT,ABSENT,ABSENT,NEG,ABSENT,ABSENT
33,3379,John Taink,4,2026-04-27 12:37:36,knp update aplikasimya lama banget lemott pula,ABSENT,NEG,ABSENT,ABSENT,ABSENT,NEG,ABSENT,ABSENT
34,1029,Pengguna Google,5,2026-07-27 18:36:01,alhamdulillah es jeruk dan jus nanas nya manta...,POS,ABSENT,ABSENT,POS,ABSENT,ABSENT,ABSENT,POS
35,3541,Ammardewa Tirta,5,2026-04-20 17:26:43,sangat membantu dan mudah di pahami,ABSENT,POS,ABSENT,ABSENT,ABSENT,ABSENT,ABSENT,ABSENT
36,933,Pengguna Google,5,2026-08-01 01:25:43,layanan jelek lama gak ada pengemudi udah gitu...,NEG,NEG,ABSENT,ABSENT,NEG,NEG,ABSENT,ABSENT
37,3565,Nova Imut,5,2026-04-19 17:40:21,grab top bgt paling banyak diskounnya sangat m...,ABSENT,ABSENT,POS,ABSENT,ABSENT,ABSENT,POS,ABSENT
38,57,Pengguna Google,5,2026-09-01 13:24:46,pesanan diterima dengan cepat dan ojol ramah,POS,ABSENT,ABSENT,ABSENT,POS,ABSENT,ABSENT,ABSENT
39,1081,Pengguna Google,5,2026-07-25 15:49:38,sudah jadi aplikasi yang sangat bermanfaat,ABSENT,ABSENT,ABSENT,ABSENT,ABSENT,ABSENT,ABSENT,ABSENT
40,1409,Pengguna Google,5,2026-07-12 03:28:20,berguna untuk perjalanan jauh dan murah,ABSENT,ABSENT,POS,ABSENT,ABSENT,ABSENT,ABSENT,ABSENT
41,2780,Pengguna Google,5,2026-05-20 21:55:05,bapaknya baik ramah banget kami dibantuin bawa...,POS,ABSENT,ABSENT,ABSENT,POS,ABSENT,ABSENT,ABSENT
42,376,Pengguna Google,5,2026-08-19 20:18:34,terimakasi atas pesanan tepat waktunya,POS,ABSENT,ABSENT,ABSENT,ABSENT,ABSENT,ABSENT,ABSENT
43,1918,Pengguna Google,5,2026-06-25 21:20:56,kerjanya bagus ramah dan tepat waktu dan aman ...,POS,ABSENT,ABSENT,ABSENT,POS,ABSENT,ABSENT,ABSENT
44,2162,Pengguna Google,5,2026-06-17 16:17:48,pakai aplikasi ini sungguh luar biasa bagus,ABSENT,ABSENT,ABSENT,ABSENT,ABSENT,ABSENT,ABSENT,ABSENT
45,3583,Daniel sitorus,5,2026-04-18 22:06:59,salah satu apk yang sangat membatu,ABSENT,ABSENT,ABSENT,ABSENT,ABSENT,ABSENT,ABSENT,ABSENT
46,3355,nur holisoh,5,2026-04-28 15:26:12,suka pake aplikasi ini karena klo dkeet murah ...,ABSENT,ABSENT,POS,ABSENT,ABSENT,ABSENT,POS,ABSENT
47,1479,Pengguna Google,5,2026-07-09 06:15:05,memudahkan setiap perjalanan bikin gk ribet,ABSENT,ABSENT,ABSENT,ABSENT,ABSENT,ABSENT,ABSENT,ABSENT
48,901,Pengguna Google,5,2026-08-02 07:16:52,pelayanan tanpa ribet sat set jos jis,ABSENT,ABSENT,ABSENT,ABSENT,ABSENT,ABSENT,ABSENT,ABSENT
49,2182,Pengguna Google,5,2026-06-16 22:10:19,terimakasih ya grab sudah beberapa kali memang...,ABSENT,ABSENT,ABSENT,ABSENT,ABSENT,ABSENT,ABSENT,ABSENT

In [32]:
def classification_report(y_true : np.array, y_pred : np.array) -> str:
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)
    print('--------------------------')
    print('PRIMARY METRIC')
    print('--------------------------')
    for i, cat in enumerate(config.CATEGORIES):
        macro_f1 = metrics.f1_score(y_true[:, i], y_pred[:, i], average = 'macro')
        print(f"{cat} Macro F1-score: {macro_f1}")
    print('--------------------------')
    print('SECONDARY METRIC')
    print('--------------------------')
    print((y_true == y_pred).all(axis = 1).mean())
    print('--------------------------')
    print('DIAGNOSTIC METRIC')
    print('--------------------------')
    for i, cat in enumerate(config.CATEGORIES):
        recalls = metrics.recall_score(y_true[:, i], y_pred[:, i], average = None, labels = ['POS', 'ABSENT', 'NEG'])
        print(f"{cat} POS Recall: {recalls[0]}")
        print(f"{cat} ABSENT Recall: {recalls[1]}")
        print(f"{cat} NEG Recall: {recalls[2]}")
    
classification_report(df_mini[config.CATEGORIES], df_mini[np.array(config.CATEGORIES) + ".1"])
print()
classification_report(df_4o[config.CATEGORIES], df_4o[np.array(config.CATEGORIES) + ".1"])

--------------------------
PRIMARY METRIC
--------------------------
DRIVER_OPS Macro F1-score: 0.8222222222222223
APP_AND_MAPS Macro F1-score: 0.5583333333333333
PRICING_AND_BILLING Macro F1-score: 0.891471048513302
FULFILLMENT_FOOD Macro F1-score: 0.7114695340501792
--------------------------
SECONDARY METRIC
--------------------------
0.72
--------------------------
DIAGNOSTIC METRIC
--------------------------
DRIVER_OPS POS Recall: 0.6
DRIVER_OPS ABSENT Recall: 0.9705882352941176
DRIVER_OPS NEG Recall: 0.7272727272727273
APP_AND_MAPS POS Recall: 0.0
APP_AND_MAPS ABSENT Recall: 0.8235294117647058
APP_AND_MAPS NEG Recall: 0.9333333333333333
PRICING_AND_BILLING POS Recall: 0.6666666666666666
PRICING_AND_BILLING ABSENT Recall: 0.9714285714285714
PRICING_AND_BILLING NEG Recall: 0.9166666666666666
FULFILLMENT_FOOD POS Recall: 1.0
FULFILLMENT_FOOD ABSENT Recall: 0.9375
FULFILLMENT_FOOD NEG Recall: 1.0

--------------------------
PRIMARY METRIC
--------------------------
DRIVER_OPS Macro F1-score: 0.8412040374909878
APP_AND_MAPS Macro F1-score: 0.6018099547511312
PRICING_AND_BILLING Macro F1-score: 0.8742857142857142
FULFILLMENT_FOOD Macro F1-score: 1.0
--------------------------
SECONDARY METRIC
--------------------------
0.78
--------------------------
DIAGNOSTIC METRIC
--------------------------
DRIVER_OPS POS Recall: 0.6
DRIVER_OPS ABSENT Recall: 1.0
DRIVER_OPS NEG Recall: 0.7272727272727273
APP_AND_MAPS POS Recall: 0.0
APP_AND_MAPS ABSENT Recall: 0.8823529411764706
APP_AND_MAPS NEG Recall: 1.0
PRICING_AND_BILLING POS Recall: 0.6666666666666666
PRICING_AND_BILLING ABSENT Recall: 0.9428571428571428
PRICING_AND_BILLING NEG Recall: 0.9166666666666666
FULFILLMENT_FOOD POS Recall: 1.0
FULFILLMENT_FOOD ABSENT Recall: 1.0
FULFILLMENT_FOOD NEG Recall: 1.0

In [34]:
for c in config.CATEGORIES:
    print(df_4o[c].value_counts())

DRIVER_OPS
ABSENT    34
NEG       11
POS        5
Name: count, dtype: int64
APP_AND_MAPS
ABSENT    34
NEG       15
POS        1
Name: count, dtype: int64
PRICING_AND_BILLING
ABSENT    35
NEG       12
POS        3
Name: count, dtype: int64
FULFILLMENT_FOOD
ABSENT    48
NEG        1
POS        1
Name: count, dtype: int64

based on the data distribution, food category is very small hence will be dropped. Furthermore, the POS also come to a very small percentage of the data. 
Cause generally the positive comment is on overall generic stuff, they mostly clustered to ABSENT. From the business perspective, NEG is much more informative to fix problem in the company.